### ISSUE TITLE
support for X1 X2 X3

### ISSUE THREAD

**Issue by BisarAhmed** [OpenLI-NZ/openli#103]
we have a IMS vendor who support X1 X2 X3 to integrate with LI, i have read the wiki and documentation also watched the tutorial but could not find any related information .

does open LI support  X1 X2 X3 protocols? or can we integrate the Open LI with the service that the vendor provide?

**Comment by salcock** [comment]
Hi there,

At present, OpenLI does not directly support interfacing with the X1 / X2 / X3 protocols. Adding support for these is definitely on our roadmap for the coming year.

In the meantime, if you are able to mirror the relevant SIP and RTP traffic (without the X2 / X3 headers) from your IMS into an OpenLI collector instance, then OpenLI would be able to perform the interception based on that.

If you're interesting in more information, or want to register your interest in getting early access to the X1/X2/X3 support as we are developing it, then send an email to hello@openli.nz and the support team at SearchLight will assist you further.
