### ISSUE TITLE
Supporting Nokia 7750 router with layer-3-encap header-type ip-udp-shim

### ISSUE THREAD

**Issue by niekvanderven** [OpenLI-NZ/openli#84]
Hi,
We are checking how we can use this great software for both data and voip taps.
Is there support for receiving the traffic from a Nokia 7750 SR (former Alcatel Lucent SROS) ?
We can sent the traffic from a IP tap with the added header:  layer-3-encap header-type ip-udp-shim
config below would use a source/dest ip and source/dest UDP port eg 601 in the config below: /configure mirror mirror-dest "601" admin-state enable
    /configure mirror mirror-dest "601" encap { }
    /configure mirror mirror-dest "601" encap { layer-3-encap }
    /configure mirror mirror-dest "601" encap { layer-3-encap header-type ip-udp-shim }
    /configure mirror mirror-dest "601" encap { layer-3-encap direction-bit true }
    /configure mirror mirror-dest "601" encap { layer-3-encap router-instance "Base" }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway ip-address }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway ip-address source 10.10.10.1 }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway ip-address destination 192.168.168.254 }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway udp-port }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway udp-port source 601 }
    /configure mirror mirror-dest "601" encap { layer-3-encap gateway udp-port destination 601 }

The intercept itself will send also the additional details like intercept-id and the session-id:
 /li li-source "601" admin-state enable
    /li li-source "601" sap 1/1/c3/1:0 { }
    /li li-source "601" sap 1/1/c3/1:0 { intercept-id 20210319 }
    /li li-source "601" sap 1/1/c3/1:0 { session-id 1 }
    /li li-source "601" sap 1/1/c3/1:0 { ingress true }
    /li li-source "601" sap 1/1/c3/1:0 { egress true }

Thanx in advance for the help and support !
Niek van der Ven

**Comment by salcock** [comment]
Hi Niek,

We do have support for converting the Alcatel Lucent shim intercept format into ETSI-compliant intercept records -- assuming that the shim format hasn't changed since they became Nokia, this is probably what you're looking for.

There are two bits of configuration you'll need to make this work:
 * On your collector(s), use the `alumirrors` config option to tell OpenLI how to identify the shim-wrapped packets. [See here for more details](https://github.com/wanduow/openli/blob/master/doc/CollectorDoc.md#alu-mirror-configuration) and [an example is here](https://github.com/wanduow/openli/blob/master/doc/exampleconfigs/collector-example.yaml#L40).
 * When configuring the intercept itself, set the `vendmirrorid` configuration option to match the intercept-id that you configured on your Nokia hardware. [Here's an example](https://github.com/wanduow/openli/blob/master/doc/exampleconfigs/running-intercept-example.yaml#L83).

Hopefully that will work for you in your situation -- let me know how it goes :)

Shane

**Comment by niekvanderven** [comment]
Hi Shane,
Thank you for the reply and help, really appreciated !
So my setup is as follow:
Customer VPLS between PE1 and PE3 with ip's 172.16.16.1/24 and 172.16.16.2/24

Mirror source on PE1 to capture the VPLS service in both directions.

Miror Destination with header-type ip-udp-shim and its contents of:
Source ip 10.10.10.1
Source port: UDP 601
Destination IP: 192.168.168.254
Destination port: UDP 601
Intercept-id 20210319 
Session-id 1

On the PE2 we have a port and Vlan 601 with ip 192.168.268.253/24
This PE will receive the mirror from PE1

OpenLi server is attached to the port with Vlan 601 and has ip 192.168.168.254/24 and route back for 10.10.10.1 towards 192.168.168.253.

on the collector config:
alumirrors:
 - ip: 192.168.168.254
   port: 601
inputs:
 - uri: eth1          # capture on interface eth1
   threads: 2           # use 2 processing threads for this input

in the running-intercept-config.yaml:
 - liid:  20210319 
   authcountrycode: NL          # Authorisation country code
   deliverycountrycode: NL      # Delivery country code
   mediator: 6001               # ID of the mediator to send intercept via
   user: "edwardnigma"          # Username for the target
   agencyid: "Police"           # ID of agency to send intercept to
   accesstype: "LAN"            # Access tech used by the target to access IP
   staticips:
     - iprange: "172.16.16.0/24"
       sessionid: 1


Now i'am not sure what to do with the running-intercept config, is this correct as we are tapping a VPLS and do not use Radius/AAA users etc... ?
Then next question is if we can "Fake" the agency with a test so we can see the packets coming in and what we will send out without really sending as its in a Lab environment.
The input is now only specifying a interface, if i change it to eth1.601 the config has errors and reports it in the syslog, is this the correct way or can we specify also a Vlan on a port ?
The logging to /var/log/openli folder isn't working, created the folder with "777" right and group openli/openli, for now we get all the logs in syslog, but would be nice if i can get it in the right folders, any idea ?
If we would like to start a Pcap of the incoming packets, how do we define that, i can't find an example to do so ?

Again thank you for the support and great project.
Niek van der Ven

**Comment by salcock** [comment]
Hi Niek,

In your running-intercept config, you appear to be missing the `vendmirrorid: 20210319` option that you will need for the collector to be able to recognise your shimmed packets as belonging to that intercept.

**Faking the agency:** you can use the `tracepktdump` tool from the `libtrace4-tools` package to act as a dummy agency handover. First, add your dummy agency to your running-intercept config, e.g.
```
agencies:
  - hi3address: <a local IP address>
    hi3port: 45555
    hi2address: <a local IP address>
    hi2port: 45554
    agencyid: testing
```

Then you can run `tracepktdump` to receive HI3 as follows:
```
   tracepktdump etsilive:<IP address>:45555
```

This will decode and dump any received ETSI intercept records to the terminal (assuming the intercept is configured with `testing` as the agencyid, of course).

**Filtering by VLAN:** you may be able to use the `filter` option when specifying your input in the collector config file to limit your input to just a specific VLAN. For instance:
```
inputs:
  - uri: eth1
    threads: 2
    filter: "vlan 601"
``` 

**Logging:** If you use rsyslog, we've provided config files that will tell it to write the OpenLI logs into /var/log/openli. Copy the files in `/etc/openli/rsyslog.d` into `/etc/rsyslog.d` and then restart the rsyslog service.

If `/etc/rsyslog.d` doesn't exist, you'll first need to install rsyslog using your usual package manager.

If you use a different logging system, such as `syslog-ng`, you'll need to provide your own configuration unfortunately. 

**Pcap:** this is indeed possible, if you follow these steps:
 1. In your mediator configuration file, set the `pcapdirectory` option to the location where you want your pcaps to end up and the `pcaprotatefreq` to how often you want the resulting files to be rotated (in minutes).
 2. Restart the mediator.
 3. Now, any intercept that has an `agencyid` of `pcapdisk` will now be automatically written to a pcap file by the mediator. Note that the packets in the pcap will NOT have any of the ETSI headers -- just the original IP packet itself is written to the pcap.

**Comment by niekvanderven** [comment]
Hi Shane,
Thank you again for the clear information, let me test it in the coming days and i revert back to you, 
hopefully with good results so i can document it and use for a demo and take it from there.
Niek van der Ven
