### ISSUE TITLE
Collector crashes into a segfault

### ISSUE THREAD

**Issue by thuroc** [OpenLI-NZ/openli#92]
Hello salcock,

we have a problem with our openLI installation and after some troubleshooting we can't find the cause. In some cases the collector will crashes into a Segmentation fault.

As you can see in the sip trace, we have a call from A to B and another call from B to C a the same time. In this case B is the monitored participant and he has configured a forwarding to C. Both calls should be recorded on the same openLI maschine. The call from B to C is technically a completely new call with a new call-id, new branches, new tags, but with the same From-Name and the same P-Asserted-Identity header.

At the moment where the B to C Call leaves the openLI system and the C-B "100 Try" returns, the collector crashes every time.

Interestingly, we cannot determine this behavior if A, B and C start a conference and the calls are set up one after the other. It looks as if the error would only occur if the monitored customer has two simultaneous calls in the "100 Try" state.

Could you have a look at this please?

Regards Sven

openLI Version: Current Master, compiled this morning
commit 1ea1ade99d5ae336127a3c4dcda91dc5b8e5e10e (HEAD -> master, tag: 1.0.13-1, origin/master, origin/HEAD)

SIP-Trace on the openLI system:
[openLI_trace.txt](https://github.com/wanduow/openli/files/8427754/openLI_trace.txt)

Collector strace:
nanosleep({tv_sec=0, tv_nsec=1000000}, OpenLI: creating new VOIP session for LIID ABCDEF (callID=1DA06981-624D8E190006E192-FC547700)
NULL) = 0
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by salcock** [comment]
Hi Sven,

Would you be able to provide me with a pcap of the SIP traffic that would be seen by the collector for the call that is causing the crashes? I could then replay the traffic in my lab environment and debug the crashing directly.

You can email it to me directly at salcock@waikato.ac.nz -- any traffic data that I receive would be treated as strictly confidential.

If you have any questions, drop me a line directly at the same email address.

Thanks.

**Comment by thuroc** [comment]
Hallo salcock,

thank you for your support. 

My email has just been sent. If you haven't received anything yet, please let us know.

Regards

**Comment by salcock** [comment]
Yep, I've got your email. I'll get back to you shortly...
