### ISSUE TITLE
Is there is Any way to make OPEN-Li logs in customized Place

### ISSUE THREAD

**Issue by tamilselvanakp** [OpenLI-NZ/openli#93]
Is there is Any way to make OPEN-Li logs in customized Place?

**Comment by tamilselvanakp** [comment]
Kindly help me to figure out the issue

**Comment by salcock** [comment]
Yes, but it will depend on which logging daemon you are using on the host that is running OpenLI.

If you are using rsyslog, we provide suitable rsyslog config files which can be used to change the file that each OpenLI component logs to. You'll find these in `/etc/openli/rsyslog` -- edit the files, then copy them into your rsyslog config directory (usually `/etc/rsyslog`) and then restart the rsyslog daemon.

If you are using syslog-ng, you will have to edit the `/etc/syslog-ng/syslog-ng.conf` file to add rules for the OpenLI components.
